# Generated by Django 5.2.8 on 2025-11-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'چندگزینه\u200cای'), ('TF', 'درست/غلط'), ('FILL', 'جای خالی'), ('TEXT', 'تشریحی')], default='MCQ', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('inequality', 'نامعادله'), ('identity', 'اتحادها')], default='inequality', max_length=50),
        ),
    ]
