# Generated by Django 5.2.8 on 2026-02-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('step_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو'), ('question', 'سؤال'), ('finish', 'پایان')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='lesson_videos/')),
                ('question', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AddField(
            model_name='step',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lessons.topic'),
        ),
    ]
